### PR TITLE
Added Dockerfile supporting GPUs, Jupyter notebooks plus corresponding instructions

### PR DESCRIPTION
**Pull request by behackl**
This approach still has a few issues which have to be investigated before we can proceed:

- Hard restriction: opencl can only utilize the CPU from within virtual environments, this might be a big blow to performance.
- Hard restriction: ... and the support for newer CPUs is not great: the `pocl-opencl-icd` package apparently does not have a proper fallback for unknown CPUs (mine was recognized as *generic* and I was unable to run the test suite from within the container).

TODOs:
- [x] Setup a pipeline for automated building / pushing images to dockerhub (or the GitHub package registry?)
- [ ] Investigate whether compatibility with newer CPUs can be obtained by compiling a newer version of `pocl-opencl-icd` than what is available via `apt`.

### CODE REVIEW

**Comment by behackl** [comment]
While the support for newer CPUs might still not be great, I've built a better docker image which (provided the container is started appropriately) is also able to utilize the GPUs of the host system. I've managed to (after additionally installing `pytest`) let the test suite pass from within the container on my local machine.

This now also includes a new workflow to automatically build the image and push it to the GitHub container registry. If everything works as expected, the image should be accessible via
```
docker pull ghcr.io/kbredies/graptor:latest
```
which is, at that point, probably also worth mentioning in the main README.

Ready to be merged, @kbredies! :-)

**Comment by behackl** [comment]
I've included some more features after our chat today:

- `pytest` is now preinstalled
- instructions for X11 forwarding are included in `docker/readme.md` + dependencies are included in the image
- and instructions to use the container to startup a Jupyter notebook server (which might be easier to setup than X11 forwarding) have also been included in `docker/readme.md` + corresponding dependencies are included in the image

**Comment by behackl** [comment]
With the docker image corresponding to the latest release being pushed to the GitHub Container Registry, it might also be possible to setup an interactive playground for the library using https://mybinder.org/, might be worth investigating.

**Comment by kbredies** [comment]
>     * Hard restriction: ... and the support for newer CPUs is not great: the `pocl-opencl-icd` package apparently does not have a proper fallback for unknown CPUs (mine was recognized as _generic_ and I was unable to run the test suite from within the container).

One possibility for better CPU support is the [Intel® CPU Runtime for OpenCL™ Applications](https://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz) package. It seems, however, that this has to be installed manually. It also depends on installing `lsb-core` via `apt`.

**Comment by behackl** [comment]
@kbredies, regarding the intel support: are the instructions added in e70958c correct? (I can't test it locally.)

I've added a note regarding possible further steps to get X11 forwarding working in 8b23009, thanks!

**Comment by kbredies** [comment]
> The latest release does not support Ubuntu 22.04 either:

There is a chance that it will still work on Ubuntu 22.04. Maybe one could try a hack like setting `DISTRIB_RELEASE=20.04` in `/etc/lsb-release`.

**Comment by behackl** [comment]
In 2da1403, `pocl-opencl-icd` is added to the list of installed dependencies. With this, I think the image is good enough to be built for now; I recommend merging this to see whether the action builing the image and pushing it to the container registry works correctly.

If it does, I'll prepare a Jupyter notebook with the quickstart example which could then be run from https://mybinder.org/. :+1:

**Pull request merged**
